// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/blog/internal/server"
	"github.com/blog/internal/service"
	"github.com/blog/pkg/app"
)

// Injectors from wire.go:

func wireApp() *app.App {
	blogService := service.NewBlogService()
	httpServer := server.NewHttpServer(blogService)
	grpcServer := server.NewGrpcServer(blogService)
	appApp := app.NewApp(httpServer, grpcServer)
	return appApp
}
